langage: node_js
node_js:
- 6.9.1

# branches:
#   only:
#   - master

before_install:
  - npm install -g gulp
  - npm install -g bower

install:
  - npm install
  - bower install

script: npm run build