language: node_js
node_js:
- node

notifications:
  email: false

branches:
  only:
  - master

before_install:
- npm install -g gulp
- npm install -g bower

install:
- npm install
- bower install

script: npm run build

addons:
  ssh_known_hosts: $SSH_HOST

before_deploy:
- openssl aes-256-cbc aes-256-cbc -K $encrypted_<...>_key -iv $encrypted_<...>_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  script: npm run deploy
  skip_cleanup: true
  on:
    branch: master
