language: node_js
node_js:
- node

notifications:
  email: false

branches:
  only:
  - master
  - develop

cache:
  directories:
  - node_modules
  - bower_components

addons:
  ssh_known_hosts: vps.alexandrebonhomme.fr

before_install:
- npm install -g gulp
- npm install -g bower

install:
- npm install
- bower install

script: npm run build

before_deploy:
- openssl aes-256-cbc -K $encrypted_38f5841c65a5_key -iv $encrypted_38f5841c65a5_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- chmod 600 deploy_rsa
- eval "$(ssh-agent -s)"
- ssh-add deploy_rsa

deploy:
  - provider: script
    script: npm run deploy-prod
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: npm run deploy
    skip_cleanup: true
    on:
      branch: develop
