language: node_js
node_js:
  - node

# branches:
#   only:
#   - master

before_install:
  - npm install -g gulp
  - npm install -g bower

install:
  - npm install
  - bower install

script: npm run build

deploy:
  provider: script
  script: npm run deploy